### ISSUE TITLE
phydrus doesn`t work with latest official Hydrus1D GUI

### ISSUE THREAD

**Issue by mrustl** [phydrus/source_code#1]
Hi @raoulcollenteur, 

I tried to use the latest Hydrus version (4.17.0140 | 15.11.2018 | [Hydrus1D_4.17.0140.exe](https://www.pc-progress.com/en/Download.aspx?back=Default.aspx%3fH1d-downloads)) and executable `H1D_CALC.EXE` with `phydrus` but only got unsuccessful model runs. Only by using `hydrus.exe` from this repo I was able to get proper model runs. Can you tell me which version of Hydrus1D you are using here: https://github.com/phydrus/source_code/tree/main/source

**Comment by raoulcollenteur** [comment]
Hi @mrustl,

We're using the latest open sourced release from the Hydrus-1D developers, 4.08: https://www.pc-progress.com/en/Default.aspx?H1D-description#k8

Cheers,
Raoul

**Comment by mrustl** [comment]
Ah ok, thanks for that hint! Too bad that they don`t also publish the source code for the latest version!
